### ISSUE TITLE
titleタグが複数ある場合

### ISSUE THREAD

**Issue by RyoMazda** [HonoMi/chrome_extension_copy_urls#3]
titleタグが複数あるページがあり、その時ctrl+yすると[]内が汚い
はじめの一つだけから取ってくればいい？
例えば
* [Packages - The Go Programming Languagesubmit search](https://golang.org/pkg/)
* [Cloud Architect – Professional Certification Preparation for Googleplaylist_addthumb-downthumb-upmenunavigation-dashboardnavigation-libraryarrow-drop-downarrow-drop-downsearcharrow-drop-downBack to Learning PathsLP Box CoursesLP Box quizLP Box LabtwitterlinkedinyoutubefacebookTrialTrialGreen DiamondYellow DiamondCheckCheckCheckCheckCheckCheckCheckCheckCheckCheckCheckCheckCheckCheckcheck2check2check2check2check2check2check2check2check2check2check2check2check2check2check2check2check2](https://cloudacademy.com/learning-paths/cloud-architect-professional-certification-preparation-for-google-35/) #

**Comment by HonoMi** [comment]
Fixed.

**Comment by HonoMi** [comment]
Fixed.
